---
# configuration for sops.
# each machine i use ansible from has a unique age key
#
# i also maintain a user key which resides outside of my machines in a secure location.
# (just in case i lose access to my machines).
#
# sops will go ahead and encrypt secrets with all of the specified keys.

keys:
  - users:
      - &jack age1xkn8hwvzs8drdfz96ypv3pe5cudj5l00pz96z7e8ygpakt6h8cesp969f9
  - hosts:
      - &mba01 age1svunme2cf37ruat8z9sv34uu4y0m2r489reks7vusllz49mpwedqv372vr

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *jack
          - *mba01
