---
- name: Ensure Vaultwarden directory exists
  ansible.builtin.file:
    path: "{{ vaultwarden_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure Vaultwarden data directory exists
  ansible.builtin.file:
    path: "{{ vaultwarden_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vaultwarden_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"

- name: Ensure Vaultwarden container is running
  community.docker.docker_compose_v2:
    project_src: "{{ vaultwarden_dir }}"
    state: present
    pull: always

- name: Allow Vaultwarden port through the firewall
  ansible.posix.firewalld:
    port: 8000/tcp
    permanent: true
    state: enabled
    immediate: true
