- name: Update all packages to the latest version
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Python3 and Pip
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Install Podman Compose
  ansible.builtin.pip:
    name: podman-compose
    state: present
    executable: pip3
