---
- name: Ensure NFS common packages are installed
  apt:
    name: nfs-common
    state: present
    update_cache: true

- name: Unmount NFS shares (if mounted)
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ nfs_server }}:{{ item.path }}"
    fstype: nfs
    state: unmounted
  loop: "{{ nfs_shares }}"

- name: Create NFS share mount points
  file:
    path: "{{ item.mount_point }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop: "{{ nfs_shares }}"

- name: Mount NFS shares with systemd automount and netdev
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ nfs_server }}:{{ item.path }}"
    fstype: nfs
    opts: "defaults,_netdev,x-systemd.automount"
    state: mounted
  loop: "{{ nfs_shares }}"