---
- name: Ensure NFS common packages are installed
  apt:
    name: nfs-common
    state: present

- name: Unmount NFS shares
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ nfs_server }}:{{ item.path }}"
    fstype: nfs
    state: unmounted
  with_items: "{{ nfs_shares }}"

- name: Create NFS share mount points
  file:
    path: "{{ item.mount_point }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  with_items: "{{ nfs_shares }}"

- name: Mount NFS shares
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ nfs_server }}:{{ item.path }}"
    fstype: nfs
    opts: defaults
    state: mounted
  with_items: "{{ nfs_shares }}"