---
- name: Ensure required packages are installed
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Ensure Docker keyring directory exists
  file:
    path: "{{ docker_keyring_dir }}"
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: "{{ docker_key_path }}"
    mode: '0644'

- name: Add Docker apt repository
  apt_repository:
    repo: "{{ docker_repo_entry }}"
    filename: docker
    state: present

- name: Update apt cache
  apt:
    update_cache: true

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: true


- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_users | length > 0

- name: Create Docker data directory
  ansible.builtin.file:
    path: "{{ docker_data_dir }}"
    state: directory
    owner: root
    group: docker
    mode: '0755'