---
- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker repository
  ansible.builtin.command:
    cmd: "dnf config-manager --add-repo {{ docker_repo_url }}"
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true

- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_users | length > 0
